spring:
  datasource:
    url: jdbc:postgresql://db.xtpzfhfmldlmexwlchhl.supabase.co:5432/postgres
    username: postgres
    password: pAy*&2Ep%L98ZKq
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: swiftaero290@gmail.com
    password: bckqfapgzhgbdxfs

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 724857527525-3kehgvohkiimvhj9vj3pijois33kn1id.apps.googleusercontent.com
            client-secret: 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

binar:
  app:
    jwtSecret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    #    NEED DISCUSSION WITH FE TEAM
    jwtExpirationMs: 3600000
    baseUrl: http://localhost:8080/api/


cloudinary:
  cloud_name: drpx4fqwg
  api_key: 846117517621741
  api_secret: zRFUUVUQghNgcPAuv5DN7Qqlte0

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui
    operations-sorter: method
