spring:
  datasource:
    #    Sesuaikan dengan DB Masing masing
    url:  jdbc:postgresql://roundhouse.proxy.rlwy.net:28519/railway
    username: postgres
    password: G4f5G*GbeDBgcdd53-ABbBfGB-DF22a1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.gmail.com
    port: 587
    username: depanbelakang944@gmail.com
    password: bglxmoxhroikcpua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 724857527525-3kehgvohkiimvhj9vj3pijois33kn1id.apps.googleusercontent.com
            client-secret: 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

binar:
  app:
    jwtSecret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629
    #    NEED DISCUSSION WITH FE TEAM
    jwtExpirationMs: 3600000
    baseUrl: http://localhost:8080/api/


cloudinary:
  cloud_name: drpx4fqwg
  api_key: 846117517621741
  api_secret: zRFUUVUQghNgcPAuv5DN7Qqlte0
